### ISSUE TITLE
Add French variant for the official website

### ISSUE THREAD

**Issue by PersoSirEduard** [LiveGuard-Streaming/Public-Website#1]
Currently, the website is only in English. To satisfy Quebec's government policies, we need to have our website in French as well. We can do so by allowing the user to change the language with the URL (or through a button click on the website that would redirect the user to the right URL):
_E.g._
www.liveguard.ca/en/ _(English)_
www.liveguard.ca/fr/ _(French)_

This can be achieved easily by reorganizing the source files for the website as follows:

![Image](https://github.com/LiveGuard-Streaming/Public-Website/assets/59216720/056ef2e2-834f-4b5e-a6ad-2ae52532fc1e)

In the example above, the index.html files are all the same, but in different languages (under their respective parent folder). Furthermore, the CSS and JS files can be shared by all HTML files since they are language-independent.

Ask @JaeeunJ for any additional help.

**Comment by fredjarjour** [comment]
0f2a98a
